/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liteProto_LlpJavaNative */

#ifndef _Included_com_liteProto_LlpJavaNative
#define _Included_com_liteProto_LlpJavaNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpNewEnv
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_liteProto_LlpJavaNative_llpNewEnv
  (JNIEnv *, jclass);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpFreeEnv
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_liteProto_LlpJavaNative_llpFreeEnv
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpRegMes
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_liteProto_LlpJavaNative_llpRegMes
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpRegSMes
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_liteProto_LlpJavaNative_llpRegSMes
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpMessageNew
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_liteProto_LlpJavaNative_llpMessageNew
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpMessageClr
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_liteProto_LlpJavaNative_llpMessageClr
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpMessageFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_liteProto_LlpJavaNative_llpMessageFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpMessageName
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_liteProto_LlpJavaNative_llpMessageName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpWmesInteger
 * Signature: (JLjava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_liteProto_LlpJavaNative_llpWmesInteger
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpWmesReal
 * Signature: (JLjava/lang/String;D)I
 */
JNIEXPORT jint JNICALL Java_com_liteProto_LlpJavaNative_llpWmesReal
  (JNIEnv *, jclass, jlong, jstring, jdouble);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpWmesString
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_liteProto_LlpJavaNative_llpWmesString
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpWmesBytes
 * Signature: (JLjava/lang/String;[B)I
 */
JNIEXPORT jint JNICALL Java_com_liteProto_LlpJavaNative_llpWmesBytes
  (JNIEnv *, jclass, jlong, jstring, jbyteArray);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpWmesMessage
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_liteProto_LlpJavaNative_llpWmesMessage
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpRmesInteger
 * Signature: (JLjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_liteProto_LlpJavaNative_llpRmesInteger
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpRmesReal
 * Signature: (JLjava/lang/String;I)D
 */
JNIEXPORT jdouble JNICALL Java_com_liteProto_LlpJavaNative_llpRmesReal
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpRmesString
 * Signature: (JLjava/lang/String;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_liteProto_LlpJavaNative_llpRmesString
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpRmesBytes
 * Signature: (JLjava/lang/String;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_liteProto_LlpJavaNative_llpRmesBytes
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpRmesMessage
 * Signature: (JLjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_liteProto_LlpJavaNative_llpRmesMessage
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpRmesSize
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_liteProto_LlpJavaNative_llpRmesSize
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpOutMessage
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_liteProto_LlpJavaNative_llpOutMessage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpInMessage
 * Signature: ([BJ)I
 */
JNIEXPORT jint JNICALL Java_com_liteProto_LlpJavaNative_llpInMessage
  (JNIEnv *, jclass, jbyteArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
